/**
 * 管理画面操作履歴のアクションタイプ
 * アプリ側で管理するため、DBマイグレーションなしで追加可能
 */
export const AdminActionType = {
  // 認証/管理者管理
  LOGIN: 'LOGIN',
  LOGOUT: 'LOGOUT',
  CREATE_ADMIN: 'CREATE_ADMIN',
  UPDATE_ADMIN: 'UPDATE_ADMIN',
  DELETE_ADMIN: 'DELETE_ADMIN',
  RESET_PASSWORD: 'RESET_PASSWORD',
  CREATE_ROLE: 'CREATE_ROLE',
  UPDATE_ROLE: 'UPDATE_ROLE',
  DELETE_ROLE: 'DELETE_ROLE',
  CREATE_EXCLUSION_LINK: 'CREATE_EXCLUSION_LINK',
  UPDATE_EXCLUSION_LINK: 'UPDATE_EXCLUSION_LINK',
  DELETE_EXCLUSION_LINK: 'DELETE_EXCLUSION_LINK',
  ACCESS: 'ACCESS',

  // ポイント関連
  POINT_GRANT: 'POINT_GRANT',
  POINT_PLAN_CREATE: 'POINT_PLAN_CREATE',
  POINT_PLAN_UPDATE: 'POINT_PLAN_UPDATE',
  POINT_PLAN_DELETE: 'POINT_PLAN_DELETE',
  POINT_PLAN_TOGGLE: 'POINT_PLAN_TOGGLE',

  // アイテム関連
  ITEM_GRANT: 'ITEM_GRANT',
  ITEM_CREATE: 'ITEM_CREATE',
  ITEM_UPDATE: 'ITEM_UPDATE',
  ITEM_DELETE: 'ITEM_DELETE',

  // ガチャ関連
  GACHA_PROBABILITY_UPDATE: 'GACHA_PROBABILITY_UPDATE',
  GACHA_TYPE_CREATE: 'GACHA_TYPE_CREATE',
  GACHA_TYPE_UPDATE: 'GACHA_TYPE_UPDATE',
  GACHA_TYPE_DELETE: 'GACHA_TYPE_DELETE',
  GACHA_TYPE_ICON_UPDATE: 'GACHA_TYPE_ICON_UPDATE',
  GACHA_SIMULATE: 'GACHA_SIMULATE',
  GACHA_TIER_WEIGHT_UPDATE: 'GACHA_TIER_WEIGHT_UPDATE',
  GACHA_PRIZE_ASSIGNMENT_CREATE: 'GACHA_PRIZE_ASSIGNMENT_CREATE',
  GACHA_PRIZE_ASSIGNMENT_UPDATE: 'GACHA_PRIZE_ASSIGNMENT_UPDATE',
  GACHA_PRIZE_ASSIGNMENT_DELETE: 'GACHA_PRIZE_ASSIGNMENT_DELETE',
  PICKUP_GACHA_UPDATE: 'PICKUP_GACHA_UPDATE',
  FREE_GACHA_SETTINGS_UPDATE: 'FREE_GACHA_SETTINGS_UPDATE',

  // 動画関連
  VIDEO_UPLOAD: 'VIDEO_UPLOAD',
  VIDEO_UPDATE: 'VIDEO_UPDATE',
  VIDEO_DELETE: 'VIDEO_DELETE',
  VIDEO_DEFAULT_SETTINGS_UPDATE: 'VIDEO_DEFAULT_SETTINGS_UPDATE',

  // タグ関連
  TAG_CREATE: 'TAG_CREATE',
  TAG_UPDATE: 'TAG_UPDATE',
  TAG_DELETE: 'TAG_DELETE',
  TAG_ASSIGN: 'TAG_ASSIGN',
  TAG_BULK_ASSIGN: 'TAG_BULK_ASSIGN',

  // ユーザー関連
  USER_UPDATE: 'USER_UPDATE',
  USER_TAG_REMOVE: 'USER_TAG_REMOVE',

  // メッセージ関連
  MESSAGE_SEND: 'MESSAGE_SEND',

  // メッセージテンプレート関連
  RESULT_MESSAGE_TEMPLATE_CREATE: 'RESULT_MESSAGE_TEMPLATE_CREATE',
  RESULT_MESSAGE_TEMPLATE_UPDATE: 'RESULT_MESSAGE_TEMPLATE_UPDATE',
  RESULT_MESSAGE_TEMPLATE_DELETE: 'RESULT_MESSAGE_TEMPLATE_DELETE',

  // 等級マスタ関連
  PRIZE_TIER_CREATE: 'PRIZE_TIER_CREATE',
  PRIZE_TIER_UPDATE: 'PRIZE_TIER_UPDATE',
  PRIZE_TIER_DELETE: 'PRIZE_TIER_DELETE',

  // その他
  OTHER: 'OTHER',
} as const;

export type AdminActionType = typeof AdminActionType[keyof typeof AdminActionType];

/**
 * アクションタイプの日本語ラベル
 */
export const AdminActionTypeLabels: Record<AdminActionType, string> = {
  LOGIN: 'ログイン',
  LOGOUT: 'ログアウト',
  CREATE_ADMIN: '管理者作成',
  UPDATE_ADMIN: '管理者更新',
  DELETE_ADMIN: '管理者削除',
  RESET_PASSWORD: '管理者パスワード変更',
  CREATE_ROLE: '管理者ロール作成',
  UPDATE_ROLE: '管理者ロール更新',
  DELETE_ROLE: '管理者ロール削除',
  CREATE_EXCLUSION_LINK: '非表示リンク作成',
  UPDATE_EXCLUSION_LINK: '非表示リンク更新',
  DELETE_EXCLUSION_LINK: '非表示リンク削除',
  ACCESS: 'アクセス',
  POINT_GRANT: 'ポイント付与',
  POINT_PLAN_CREATE: 'ポイント購入プラン作成',
  POINT_PLAN_UPDATE: 'ポイント購入プラン更新',
  POINT_PLAN_DELETE: 'ポイント購入プラン削除',
  POINT_PLAN_TOGGLE: 'ポイント購入プラン有効/無効切替',
  ITEM_GRANT: 'アイテム付与',
  ITEM_CREATE: 'アイテム作成',
  ITEM_UPDATE: 'アイテム更新',
  ITEM_DELETE: 'アイテム削除',
  GACHA_PROBABILITY_UPDATE: 'ガチャ確率変更',
  GACHA_TYPE_CREATE: 'ガチャタイプ作成',
  GACHA_TYPE_UPDATE: 'ガチャタイプ更新',
  GACHA_TYPE_DELETE: 'ガチャタイプ削除',
  GACHA_TYPE_ICON_UPDATE: 'ガチャアイコン更新',
  GACHA_SIMULATE: 'ガチャシミュレーション',
  GACHA_TIER_WEIGHT_UPDATE: 'ガチャ等級重み更新',
  GACHA_PRIZE_ASSIGNMENT_CREATE: '景品割当作成',
  GACHA_PRIZE_ASSIGNMENT_UPDATE: '景品割当更新',
  GACHA_PRIZE_ASSIGNMENT_DELETE: '景品割当削除',
  PICKUP_GACHA_UPDATE: 'ピックアップガチャ設定更新',
  FREE_GACHA_SETTINGS_UPDATE: '無料ガチャ設定更新',
  VIDEO_UPLOAD: '動画アップロード',
  VIDEO_UPDATE: '動画更新',
  VIDEO_DELETE: '動画削除',
  VIDEO_DEFAULT_SETTINGS_UPDATE: '動画デフォルト設定更新',
  TAG_CREATE: 'タグ作成',
  TAG_UPDATE: 'タグ更新',
  TAG_DELETE: 'タグ削除',
  TAG_ASSIGN: 'タグ付与',
  TAG_BULK_ASSIGN: 'タグ一括付与',
  USER_UPDATE: 'ユーザー情報更新',
  USER_TAG_REMOVE: 'ユーザータグ削除',
  MESSAGE_SEND: 'メッセージ配信',
  RESULT_MESSAGE_TEMPLATE_CREATE: '結果メッセージテンプレート作成',
  RESULT_MESSAGE_TEMPLATE_UPDATE: '結果メッセージテンプレート更新',
  RESULT_MESSAGE_TEMPLATE_DELETE: '結果メッセージテンプレート削除',
  PRIZE_TIER_CREATE: '等級マスタ作成',
  PRIZE_TIER_UPDATE: '等級マスタ更新',
  PRIZE_TIER_DELETE: '等級マスタ削除',
  OTHER: 'その他',
};
