/* This file is auto-generated by scripts/generate-lambda-routes.mjs */
import * as route0 from '../api/admin/action-history/route.ts';
import * as route1 from '../api/admin/cache/route.ts';
import * as route2 from '../api/admin/free-gacha-settings/route.ts';
import * as route3 from '../api/admin/gacha-types/route.ts';
import * as route4 from '../api/admin/gacha-types/[code]/route.ts';
import * as route5 from '../api/admin/gacha-types/simulate/route.ts';
import * as route6 from '../api/admin/gacha-types/upload-icon/route.ts';
import * as route7 from '../api/admin/items/route.ts';
import * as route8 from '../api/admin/items/[id]/route.ts';
import * as route9 from '../api/admin/items/upload-image/route.ts';
import * as route10 from '../api/admin/messages/send/route.ts';
import * as route11 from '../api/admin/pickup/route.ts';
import * as route12 from '../api/admin/point-plans/route.ts';
import * as route13 from '../api/admin/point-plans/[id]/route.ts';
import * as route14 from '../api/admin/points/grant/route.ts';
import * as route15 from '../api/admin/prize-assignments/route.ts';
import * as route16 from '../api/admin/prize-assignments/[id]/route.ts';
import * as route17 from '../api/admin/prize-tiers/route.ts';
import * as route18 from '../api/admin/prize-tiers/[id]/route.ts';
import * as route19 from '../api/admin/referrals/route.ts';
import * as route20 from '../api/admin/result-message-templates/route.ts';
import * as route21 from '../api/admin/result-message-templates/[id]/route.ts';
import * as route22 from '../api/admin/simulator/route.ts';
import * as route23 from '../api/admin/statistics/route.ts';
import * as route24 from '../api/admin/statistics/purchase-history/route.ts';
import * as route25 from '../api/admin/tags/route.ts';
import * as route26 from '../api/admin/tags/[id]/route.ts';
import * as route27 from '../api/admin/tags/bulk-assign/route.ts';
import * as route28 from '../api/admin/users/route.ts';
import * as route29 from '../api/admin/users/[userId]/route.ts';
import * as route30 from '../api/admin/users/[userId]/tags/route.ts';
import * as route31 from '../api/admin/users/[userId]/tags/[tagId]/route.ts';
import * as route32 from '../api/admin/users/search/route.ts';
import * as route33 from '../api/admin/videos/route.ts';
import * as route34 from '../api/admin/videos/[id]/route.ts';
import * as route35 from '../api/admin/videos/default-settings/route.ts';
import * as route36 from '../api/admin/videos/presigned-url/route.ts';
import * as route37 from '../api/admin/videos/register/route.ts';
import * as route38 from '../api/admin/videos/upload/route.ts';
import * as route39 from '../api/gacha/route.ts';
import * as route40 from '../api/gacha/pickup/route.ts';
import * as route41 from '../api/gacha/prizes/route.ts';
import * as route42 from '../api/gacha/send-result/route.ts';
import * as route43 from '../api/gacha/types/route.ts';
import * as route44 from '../api/messages/pending/route.ts';
import * as route45 from '../api/messages/send-batch/route.ts';
import * as route46 from '../api/payment/create-intent/route.ts';
import * as route47 from '../api/points/balance/route.ts';
import * as route48 from '../api/points/confirm/route.ts';
import * as route49 from '../api/points/plans/route.ts';
import * as route50 from '../api/points/purchase/route.ts';
import * as route51 from '../api/points/purchase-history/route.ts';
import * as route52 from '../api/points/webhook/route.ts';
import * as route53 from '../api/prize-tiers/route.ts';
import * as route54 from '../api/referral/current/route.ts';
import * as route55 from '../api/referral/generate/route.ts';
import * as route56 from '../api/referral/history/route.ts';
import * as route57 from '../api/referral/verify/route.ts';
import * as route58 from '../api/users/[userId]/gacha-histories/route.ts';
import * as route59 from '../api/users/[userId]/items/route.ts';
import * as route60 from '../api/users/[userId]/items/[historyId]/use/route.ts';
import * as route61 from '../api/users/[userId]/stats/route.ts';
import * as route62 from '../api/users/register/route.ts';
import * as route63 from '../api/webhook/line/route.ts';

export type LambdaRouteEntry = {
  path: string;
  moduleIndex: number;
  paramNames: string[];
  regex: RegExp;
};

export const lambdaRouteModules = [
  route0,
  route1,
  route2,
  route3,
  route4,
  route5,
  route6,
  route7,
  route8,
  route9,
  route10,
  route11,
  route12,
  route13,
  route14,
  route15,
  route16,
  route17,
  route18,
  route19,
  route20,
  route21,
  route22,
  route23,
  route24,
  route25,
  route26,
  route27,
  route28,
  route29,
  route30,
  route31,
  route32,
  route33,
  route34,
  route35,
  route36,
  route37,
  route38,
  route39,
  route40,
  route41,
  route42,
  route43,
  route44,
  route45,
  route46,
  route47,
  route48,
  route49,
  route50,
  route51,
  route52,
  route53,
  route54,
  route55,
  route56,
  route57,
  route58,
  route59,
  route60,
  route61,
  route62,
  route63
];

export const lambdaRouteManifest: LambdaRouteEntry[] = [
  { path: '/api/admin/action-history', moduleIndex: 0, paramNames: [], regex: new RegExp('^/api/admin/action-history$') },
  { path: '/api/admin/cache', moduleIndex: 1, paramNames: [], regex: new RegExp('^/api/admin/cache$') },
  { path: '/api/admin/free-gacha-settings', moduleIndex: 2, paramNames: [], regex: new RegExp('^/api/admin/free-gacha-settings$') },
  { path: '/api/admin/gacha-types', moduleIndex: 3, paramNames: [], regex: new RegExp('^/api/admin/gacha-types$') },
  { path: '/api/admin/gacha-types/[code]', moduleIndex: 4, paramNames: ["code"], regex: new RegExp('^/api/admin/gacha-types/([^/]+)$') },
  { path: '/api/admin/gacha-types/simulate', moduleIndex: 5, paramNames: [], regex: new RegExp('^/api/admin/gacha-types/simulate$') },
  { path: '/api/admin/gacha-types/upload-icon', moduleIndex: 6, paramNames: [], regex: new RegExp('^/api/admin/gacha-types/upload-icon$') },
  { path: '/api/admin/items', moduleIndex: 7, paramNames: [], regex: new RegExp('^/api/admin/items$') },
  { path: '/api/admin/items/[id]', moduleIndex: 8, paramNames: ["id"], regex: new RegExp('^/api/admin/items/([^/]+)$') },
  { path: '/api/admin/items/upload-image', moduleIndex: 9, paramNames: [], regex: new RegExp('^/api/admin/items/upload-image$') },
  { path: '/api/admin/messages/send', moduleIndex: 10, paramNames: [], regex: new RegExp('^/api/admin/messages/send$') },
  { path: '/api/admin/pickup', moduleIndex: 11, paramNames: [], regex: new RegExp('^/api/admin/pickup$') },
  { path: '/api/admin/point-plans', moduleIndex: 12, paramNames: [], regex: new RegExp('^/api/admin/point-plans$') },
  { path: '/api/admin/point-plans/[id]', moduleIndex: 13, paramNames: ["id"], regex: new RegExp('^/api/admin/point-plans/([^/]+)$') },
  { path: '/api/admin/points/grant', moduleIndex: 14, paramNames: [], regex: new RegExp('^/api/admin/points/grant$') },
  { path: '/api/admin/prize-assignments', moduleIndex: 15, paramNames: [], regex: new RegExp('^/api/admin/prize-assignments$') },
  { path: '/api/admin/prize-assignments/[id]', moduleIndex: 16, paramNames: ["id"], regex: new RegExp('^/api/admin/prize-assignments/([^/]+)$') },
  { path: '/api/admin/prize-tiers', moduleIndex: 17, paramNames: [], regex: new RegExp('^/api/admin/prize-tiers$') },
  { path: '/api/admin/prize-tiers/[id]', moduleIndex: 18, paramNames: ["id"], regex: new RegExp('^/api/admin/prize-tiers/([^/]+)$') },
  { path: '/api/admin/referrals', moduleIndex: 19, paramNames: [], regex: new RegExp('^/api/admin/referrals$') },
  { path: '/api/admin/result-message-templates', moduleIndex: 20, paramNames: [], regex: new RegExp('^/api/admin/result-message-templates$') },
  { path: '/api/admin/result-message-templates/[id]', moduleIndex: 21, paramNames: ["id"], regex: new RegExp('^/api/admin/result-message-templates/([^/]+)$') },
  { path: '/api/admin/simulator', moduleIndex: 22, paramNames: [], regex: new RegExp('^/api/admin/simulator$') },
  { path: '/api/admin/statistics', moduleIndex: 23, paramNames: [], regex: new RegExp('^/api/admin/statistics$') },
  { path: '/api/admin/statistics/purchase-history', moduleIndex: 24, paramNames: [], regex: new RegExp('^/api/admin/statistics/purchase-history$') },
  { path: '/api/admin/tags', moduleIndex: 25, paramNames: [], regex: new RegExp('^/api/admin/tags$') },
  { path: '/api/admin/tags/[id]', moduleIndex: 26, paramNames: ["id"], regex: new RegExp('^/api/admin/tags/([^/]+)$') },
  { path: '/api/admin/tags/bulk-assign', moduleIndex: 27, paramNames: [], regex: new RegExp('^/api/admin/tags/bulk-assign$') },
  { path: '/api/admin/users', moduleIndex: 28, paramNames: [], regex: new RegExp('^/api/admin/users$') },
  { path: '/api/admin/users/[userId]', moduleIndex: 29, paramNames: ["userId"], regex: new RegExp('^/api/admin/users/([^/]+)$') },
  { path: '/api/admin/users/[userId]/tags', moduleIndex: 30, paramNames: ["userId"], regex: new RegExp('^/api/admin/users/([^/]+)/tags$') },
  { path: '/api/admin/users/[userId]/tags/[tagId]', moduleIndex: 31, paramNames: ["userId","tagId"], regex: new RegExp('^/api/admin/users/([^/]+)/tags/([^/]+)$') },
  { path: '/api/admin/users/search', moduleIndex: 32, paramNames: [], regex: new RegExp('^/api/admin/users/search$') },
  { path: '/api/admin/videos', moduleIndex: 33, paramNames: [], regex: new RegExp('^/api/admin/videos$') },
  { path: '/api/admin/videos/[id]', moduleIndex: 34, paramNames: ["id"], regex: new RegExp('^/api/admin/videos/([^/]+)$') },
  { path: '/api/admin/videos/default-settings', moduleIndex: 35, paramNames: [], regex: new RegExp('^/api/admin/videos/default-settings$') },
  { path: '/api/admin/videos/presigned-url', moduleIndex: 36, paramNames: [], regex: new RegExp('^/api/admin/videos/presigned-url$') },
  { path: '/api/admin/videos/register', moduleIndex: 37, paramNames: [], regex: new RegExp('^/api/admin/videos/register$') },
  { path: '/api/admin/videos/upload', moduleIndex: 38, paramNames: [], regex: new RegExp('^/api/admin/videos/upload$') },
  { path: '/api/gacha', moduleIndex: 39, paramNames: [], regex: new RegExp('^/api/gacha$') },
  { path: '/api/gacha/pickup', moduleIndex: 40, paramNames: [], regex: new RegExp('^/api/gacha/pickup$') },
  { path: '/api/gacha/prizes', moduleIndex: 41, paramNames: [], regex: new RegExp('^/api/gacha/prizes$') },
  { path: '/api/gacha/send-result', moduleIndex: 42, paramNames: [], regex: new RegExp('^/api/gacha/send-result$') },
  { path: '/api/gacha/types', moduleIndex: 43, paramNames: [], regex: new RegExp('^/api/gacha/types$') },
  { path: '/api/messages/pending', moduleIndex: 44, paramNames: [], regex: new RegExp('^/api/messages/pending$') },
  { path: '/api/messages/send-batch', moduleIndex: 45, paramNames: [], regex: new RegExp('^/api/messages/send-batch$') },
  { path: '/api/payment/create-intent', moduleIndex: 46, paramNames: [], regex: new RegExp('^/api/payment/create-intent$') },
  { path: '/api/points/balance', moduleIndex: 47, paramNames: [], regex: new RegExp('^/api/points/balance$') },
  { path: '/api/points/confirm', moduleIndex: 48, paramNames: [], regex: new RegExp('^/api/points/confirm$') },
  { path: '/api/points/plans', moduleIndex: 49, paramNames: [], regex: new RegExp('^/api/points/plans$') },
  { path: '/api/points/purchase', moduleIndex: 50, paramNames: [], regex: new RegExp('^/api/points/purchase$') },
  { path: '/api/points/purchase-history', moduleIndex: 51, paramNames: [], regex: new RegExp('^/api/points/purchase-history$') },
  { path: '/api/points/webhook', moduleIndex: 52, paramNames: [], regex: new RegExp('^/api/points/webhook$') },
  { path: '/api/prize-tiers', moduleIndex: 53, paramNames: [], regex: new RegExp('^/api/prize-tiers$') },
  { path: '/api/referral/current', moduleIndex: 54, paramNames: [], regex: new RegExp('^/api/referral/current$') },
  { path: '/api/referral/generate', moduleIndex: 55, paramNames: [], regex: new RegExp('^/api/referral/generate$') },
  { path: '/api/referral/history', moduleIndex: 56, paramNames: [], regex: new RegExp('^/api/referral/history$') },
  { path: '/api/referral/verify', moduleIndex: 57, paramNames: [], regex: new RegExp('^/api/referral/verify$') },
  { path: '/api/users/[userId]/gacha-histories', moduleIndex: 58, paramNames: ["userId"], regex: new RegExp('^/api/users/([^/]+)/gacha-histories$') },
  { path: '/api/users/[userId]/items', moduleIndex: 59, paramNames: ["userId"], regex: new RegExp('^/api/users/([^/]+)/items$') },
  { path: '/api/users/[userId]/items/[historyId]/use', moduleIndex: 60, paramNames: ["userId","historyId"], regex: new RegExp('^/api/users/([^/]+)/items/([^/]+)/use$') },
  { path: '/api/users/[userId]/stats', moduleIndex: 61, paramNames: ["userId"], regex: new RegExp('^/api/users/([^/]+)/stats$') },
  { path: '/api/users/register', moduleIndex: 62, paramNames: [], regex: new RegExp('^/api/users/register$') },
  { path: '/api/webhook/line', moduleIndex: 63, paramNames: [], regex: new RegExp('^/api/webhook/line$') }
];
