version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - cd app
      - npm install
  build:
    commands:
      - npm run db:generate
      - npm run db:deploy
      - if [ "$RUN_SEED" = "true" ]; then npm run db:seed; fi
      - if [ "$RUN_ADMIN_SEED" = "true" ]; then npm run admin:seed; fi
